# Generated by Django 4.1.7 on 2023-02-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.PositiveSmallIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('L', 'Liso'), ('O', 'Ondulado'), ('C', 'Cacheado')], default='L', max_length=1)),
                ('codigoRastreio', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peruca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50)),
                ('tamanho', models.CharField(choices=[('C', 'Curto'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('ImagemPeruca', models.ImageField(blank=True, null=True, upload_to='ImageFiles')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRastreio', models.CharField(blank=True, max_length=13, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Aprovada'), ('N', 'Não aprovada')], default='N', max_length=1)),
                ('peruca', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.peruca')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instituicao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='peruca',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perucas', to='main.instituicao'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='pessoa',
            field=models.ManyToManyField(related_name='Cabelo', through='main.Cabelo', to='main.pessoa'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='pessoa1',
            field=models.ManyToManyField(related_name='Solicitacao', through='main.Solicitacao', to='main.pessoa'),
        ),
        migrations.AddField(
            model_name='cabelo',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instituicao'),
        ),
        migrations.AddField(
            model_name='cabelo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
        ),
    ]
