# Generated by Django 4.2 on 2023-05-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peruca',
            fields=[
                ('cor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('tamanho', models.CharField(choices=[('C', 'Curto'), ('M', 'Médio'), ('C', 'Longo')], max_length=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('codRastreio', models.CharField(max_length=20)),
                ('quest1', models.TextField()),
                ('quest2', models.TextField()),
                ('quest3', models.TextField()),
                ('status', models.CharField(choices=[('analise', 'Solicitação em análise'), ('aprovado', 'Solicitação aprovada'), ('rejeitado', 'Solicitação negada'), ('caminho', 'Encomenda à caminho'), ('recebido', 'Encomenda recebida')], max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perucas', models.ManyToManyField(to='doacao.peruca')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pessoa')),
            ],
        ),
    ]
