# Generated by Django 4.2 on 2023-04-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_initial'),
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('codRastreio', models.CharField(max_length=20)),
                ('quest1', models.TextField()),
                ('quest2', models.TextField()),
                ('quest3', models.TextField()),
                ('status', models.CharField(choices=[('analise', 'Solicitação em análise'), ('aprovado', 'Solicitação aprovada'), ('rejeitado', 'Solicitação negada'), ('caminho', 'Encomenda à caminho'), ('recebido', 'Encomenda recebida')], max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='peruca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.AddField(
            model_name='doacao',
            name='perucas',
            field=models.ManyToManyField(to='doacao.peruca'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pessoa'),
        ),
    ]
