# Generated by Django 4.2 on 2023-06-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='pessoa',
        ),
    ]
