# Generated by Django 4.2.3 on 2023-07-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_peruca_foto_solicitacaoperuca_comprovante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peruca',
            name='selecionada',
        ),
    ]
