# Generated by Django 4.2.3 on 2023-07-11 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peruca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('curto', 'Peruca de tamanho curto'), ('medio', 'Peruca de tamanho médio'), ('longo', 'Peruca de tamanho longo')], max_length=50)),
                ('tipo', models.CharField(choices=[('liso', 'Peruca de cabelo liso'), ('ondulado', 'Peruca de cabelo ondulado'), ('cacheado', 'Peruca de cabelo cacheado'), ('crespo', 'Peruca de cabelo crespo')], max_length=50)),
                ('cor', models.CharField(choices=[('loiro', 'Peruca de cabelo loiro'), ('ruivo', 'Peruca de cabelo ruivo'), ('preto', 'Peruca de cabelo preto'), ('castanho', 'Peruca de cabelo castanho'), ('grisalho', 'Peruca de cabelo grisalho')], max_length=50)),
                ('selecionada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPeruca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codRastreio', models.CharField(blank=True, max_length=20, null=True)),
                ('questao1', models.TextField()),
                ('questao2', models.TextField()),
                ('questao3', models.TextField()),
                ('status', models.CharField(choices=[('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('caminho', 'A caminho'), ('entregue', 'Entregue')], max_length=50)),
                ('peruca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.peruca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
