# Generated by Django 4.2.3 on 2023-07-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_remove_peruca_selecionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='peruca',
            name='selecionada',
            field=models.BooleanField(null=True),
        ),
    ]
