# Generated by Django 4.2.3 on 2023-07-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_peruca_selecionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoperuca',
            name='motivo_rejeição',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoperuca',
            name='status',
            field=models.CharField(choices=[('analise', 'em análise'), ('aprovado', 'aprovado'), ('rejeitado', 'rejeitado'), ('caminho', 'a caminho'), ('entregue', 'entregue')], max_length=50),
        ),
    ]
