# Generated by Django 4.2.3 on 2023-07-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_solicitacaoperuca_motivo_rejeição_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaoperuca',
            old_name='motivo_rejeição',
            new_name='motivo_rejeicao',
        ),
    ]
