# Generated by Django 4.2.3 on 2023-08-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_rename_motivo_rejeição_solicitacaoperuca_motivo_rejeicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoperuca',
            name='comprovante',
        ),
    ]
