# Generated by Django 4.2 on 2023-05-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('regiao', models.CharField(choices=[('NO', 'Norte'), ('NE', 'Nordeste'), ('SE', 'Sudeste'), ('CO', 'Centro-Oeste'), ('SU', 'Sul')], default='NO', max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('relato', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pessoa')),
            ],
        ),
    ]
