# Generated by Django 4.2 on 2023-06-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='password',
            new_name='senha',
        ),
    ]
