# Generated by Django 4.2.3 on 2023-08-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
