# Generated by Django 4.2 on 2023-04-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_depoimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='enderecos',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='enderecos',
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
