# Generated by Django 4.2 on 2023-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_doacao_alter_peruca_id_delete_solicitacao_and_more'),
        ('usuarios', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instituicao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
